### ISSUE TITLE
Realistic Rendering

### ISSUE THREAD

**Issue by styloInt** [CatherineH/python-embroidery#3]
I am thinking about implementing a realistic rendering so that at the end the user can see what it's goona look like. 

One way of doing it, is to do like inkstitch which apply a filter to every stitch https://github.com/inkstitch/inkstitch/blob/1de8487849a3f8f55d126e2687d690226e657fde/lib/svg/realistic_rendering.py

But I find this way too time consuming. I was wondering how private softwares do that.  Do you have an idea ?

**Comment by CatherineH** [comment]
I use https://github.com/CatherineH/python-embroidery/blob/1097bab7699a57c5ccac593eac4fc95c9cc17a93/pattern_utils.py#L101 to look at how things will look on the output. The other option is to view the pattern [embroidermodder](http://embroidermodder.org/news0.html). That's realistic enough for me. What are you looking for?

**Comment by styloInt** [comment]
I'm looking to have a rendering like this one : 

![Example rendering](https://i.imgur.com/9aoiFBo.png)
